### ISSUE TITLE
Unable to retrieve user's replays at this time

### ISSUE THREAD

**Issue by lifesuckz69** [polydragon/liveme-toolkit#5]
As of now EVERY replay area has the unable to retrieve error.
I fear that live.me changed something with their reply system?

**Comment by starsaillor** [comment]
no news so far. Btw have got a hold of that invite code?

**Comment by JakeFromStateCS** [comment]
Fetching user replays now require authentication.
The app will need to be updated to support authentication.

**Comment by mupumi** [comment]
Look up liveme-pro-tools.  It's a more updated live me browser.  Although it also has this issue right now

**Comment by lifesuckz69** [comment]
Yeah, but now he says something along the lines of "hanging up the head and not updating the tools anymore" and I personally have no clue what to do with the API alone. 

I found my discord invite btw, it was written somewhere on github, but not sure if it's the right one, cause nobody except TheCoder is talking there (and not even allowed to write anything)

**Comment by JakeFromStateCS** [comment]
I got pretty far with adding authentication to the liveme protools project. I'm running into issues with reverse engineering headers in the requests sent to the liveme servers at the moment. If proper headers aren't sent, a captcha is received while trying to get a single sign on code.

**Comment by mmind99** [comment]
@Brapsfemy if you could figure this out, you'd be my hero ;)  Do you have a page we could follow for updates?  Or better yet a discord we could chat on.

**Comment by lifesuckz69** [comment]
Ok, i wasted another hour to even get somewhere with the api and node and yarn and whatever thing i could download and try to paste code into with nothing but error messages, cause i probably have no clue what I'm doing.
On the Liveme Pro Tools Lewdninja said he's going to make an alternate program, so I'm gonna hope and wait for that.

**Comment by lifesuckz69** [comment]
I'm gonna close this, since we talk on liveme toolkit anyway
